apiVersion: apps/v1
kind: Deployment
metadata:
  name: microbots
spec:
  selector:
    matchLabels:
      app: microbots
  replicas: 2
  template:
    metadata:
      labels:
        app: microbots
    spec:
      containers:
      - name: microbots
        image: dontrebootme/microbot:latest
        ports:
        - containerPort: 31895
