apiVersion: apps/v1
kind: Deployment
metadata:
  name: microbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microbot
  template:
    metadata:
      labels:
        app: microbot
    spec:
      containers:
      - name: microbot
        image: xeonproc/microbot:latest
        ports:
        - containerPort: 80
