apiVersion: apps/v1
kind: Deployment
metadata:
  name: microbots
spec:
  selector:
    matchLabels:
      app: microbots
  replicas: 10
  template:
    metadata:
      labels:
        app: microbots
    spec:
      containers:
      - name: microbots
        image: dontrebootme/microbot:v1
        ports:
        - containerPort: 80
