apiVersion: v1
kind: Service
metadata:
  name: microbot-service
spec:
  type: NodePort
  selector:
    app: microbot
  ports:
  - port: 1337
    targetPort: 80
    nodePort: 31337   # Specify the NodePort number (choose a port in the range 30000-32767)
